// swift-tools-version:5.9
// Generated by fastlane :sdk lane — do not edit by hand.
import PackageDescription

let package = Package(
    name: "BidMachinePlus",
    platforms: [.iOS(.v13)],
    products: [
        .library(name: "BidMachinePlus", targets: ["BidMachinePlusTarget"]),
        .library(name: "MediationAdapterAPI", targets: ["MediationAdapterAPI"])
    ],
    targets: [
        .binaryTarget(
            name: "BidMachinePlus",
            url: "https://bidmachine-ios.s3.amazonaws.com/BidMachinePlus/0.1.1/package/BidMachinePlus.xcframework.zip",
            checksum: "fa2ac5701b33d9761aa9e4b75a7baebfefa8338fb85278754d9dabf1233bcf19"
        ),
        .binaryTarget(
            name: "BidMachine",
            url: "https://bidmachine-ios.s3.amazonaws.com/BidMachine/3.8.0/package/BidMachine.xcframework.zip",
            checksum: "b46919e3d033f35bd556e3a34a73ef9af3e27cdcac21baf476a2ee82f935a975"
        ),
        .binaryTarget(
            name: "OMSDK_Appodeal",
            url: "https://bidmachine-ios.s3.amazonaws.com/OMSDK_Appodeal/1.6.3/package/OMSDK_Appodeal.xcframework.zip",
            checksum: "3e3f791957a55085954608740455c6abad2d1f4381e5a4263242289030f7976f"
        ),
        .target(
            name: "MediationAdapterAPI",
            path: "Sources/MediationAdapterAPI"
        ),
        .target(
            name: "BidMachinePlusTarget",
            dependencies: [
                "BidMachinePlus",
                "BidMachine",
                "OMSDK_Appodeal",
                "MediationAdapterAPI"
            ],
            path: "Sources/BidMachinePlusTarget",
            sources: ["."],
            linkerSettings: [
                .linkedFramework("AdSupport"),
                .linkedFramework("AVFoundation"),
                .linkedFramework("AVKit"),
                .linkedFramework("AudioToolbox"),
                .linkedFramework("CFNetwork"),
                .linkedFramework("CoreGraphics"),
                .linkedFramework("CoreImage"),
                .linkedFramework("CoreLocation"),
                .linkedFramework("CoreMedia"),
                .linkedFramework("CoreTelephony"),
                .linkedFramework("ImageIO"),
                .linkedFramework("QuartzCore"),
                .linkedFramework("SafariServices"),
                .linkedFramework("Security"),
                .linkedFramework("StoreKit"),
                .linkedFramework("SystemConfiguration"),
                .linkedFramework("UIKit"),
                .linkedFramework("WebKit"),
                .linkedFramework("AppTrackingTransparency", .when(platforms: [.iOS])),
                .linkedLibrary("z", .when(platforms: [.iOS])),
                .linkedLibrary("sqlite3", .when(platforms: [.iOS])),
                .linkedLibrary("xml2", .when(platforms: [.iOS]))
            ]
        )
    ]
)
