// swift-tools-version:5.9
// Generated by fastlane :sdk lane — do not edit by hand.
import PackageDescription

let package = Package(
    name: "BidMachinePlus",
    platforms: [.iOS(.v13)],
    products: [
        .library(name: "BidMachinePlus", targets: ["BidMachinePlusTarget"]),
        .library(name: "MediationAdapterAPI", targets: ["MediationAdapterAPI"])
    ],
    dependencies: [
        .package(url: "https://github.com/bidmachine/BidMachine-SPM.git", exact: "3.8.0"),
        .package(url: "https://github.com/bidmachine/OMSDK-Appodeal-iOS-Package", exact: "1.6.3")
    ],
    targets: [
        .binaryTarget(
            name: "BidMachinePlus",
            url: "https://bidmachine-ios.s3.amazonaws.com/BidMachinePlus/0.1.2/package/BidMachinePlus.xcframework.zip",
            checksum: "27347b5de736445808fb84c3b8c7aeacc7a246b7b9421029bfeaeeb86c4d842b"
        ),
        .target(
            name: "MediationAdapterAPI",
            path: "Sources/MediationAdapterAPI"
        ),
        .target(
            name: "BidMachinePlusTarget",
            dependencies: [
                "BidMachinePlus",
                .product(name: "BidMachine", package: "BidMachine-SPM"),
                .product(name: "OMSDK_Appodeal", package: "OMSDK-Appodeal-iOS-Package"),
                "MediationAdapterAPI"
            ],
            path: "Sources/BidMachinePlusTarget",
            sources: ["."],
            linkerSettings: [
                .linkedFramework("AdSupport"),
                .linkedFramework("AVFoundation"),
                .linkedFramework("AVKit"),
                .linkedFramework("AudioToolbox"),
                .linkedFramework("CFNetwork"),
                .linkedFramework("CoreGraphics"),
                .linkedFramework("CoreImage"),
                .linkedFramework("CoreLocation"),
                .linkedFramework("CoreMedia"),
                .linkedFramework("CoreTelephony"),
                .linkedFramework("ImageIO"),
                .linkedFramework("QuartzCore"),
                .linkedFramework("SafariServices"),
                .linkedFramework("Security"),
                .linkedFramework("StoreKit"),
                .linkedFramework("SystemConfiguration"),
                .linkedFramework("UIKit"),
                .linkedFramework("WebKit"),
                .linkedFramework("AppTrackingTransparency", .when(platforms: [.iOS])),
                .linkedLibrary("z", .when(platforms: [.iOS])),
                .linkedLibrary("sqlite3", .when(platforms: [.iOS])),
                .linkedLibrary("xml2", .when(platforms: [.iOS]))
            ]
        )
    ]
)
